name: converrto
description: "a customizable app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.7.0
  flutter_launcher_icons: ^0.13.1
  double_back_to_close_app: ^2.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/
    - assets/nav_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: axiforma
      fonts:
        - asset: fonts/axiforma/Kastelov-Axiforma-Regular.otf
        - asset: fonts/axiforma/Kastelov  Axiforma Black.otf
          weight: 900
        - asset: fonts/axiforma/Kastelov  Axiforma Black Italic.otf
          weight: 900
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma Bold.otf
          weight: 700
        - asset: fonts/axiforma/Kastelov  Axiforma Bold Italic.otf
          weight: 700
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma Book.otf
          weight: 400
        - asset: fonts/axiforma/Kastelov  Axiforma Book Italic.otf
          weight: 400
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma ExtraBold.otf
          weight: 800
        - asset: fonts/axiforma/Kastelov  Axiforma ExtraBold Italic.otf
          weight: 800
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma Heavy.otf
          weight: 900
        - asset: fonts/axiforma/Kastelov  Axiforma Heavy Italic.otf
          weight: 900
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma Italic.otf
          weight: 400
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma Light.otf
          weight: 300
        - asset: fonts/axiforma/Kastelov  Axiforma Light Italic.otf
          weight: 300
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma Medium.otf
          weight: 500
        - asset: fonts/axiforma/Kastelov  Axiforma Medium Italic.otf
          weight: 500
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma SemiBold.otf
          weight: 600
        - asset: fonts/axiforma/Kastelov  Axiforma SemiBold Italic.otf
          weight: 600
          style: italic
        - asset: fonts/axiforma/Kastelov  Axiforma Thin.otf
          weight: 100
        - asset: fonts/axiforma/Kastelov  Axiforma Thin Italic.otf
          weight: 100
          style: italic
    - family: poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Mediumitalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 200
          style: italic
    - family: montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Mediumitalic.ttf
          weight: 500
          style: italic
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
